# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 09a9e458f249d5015fd5e78c31b50c294ee8199822afb1e3238004b8cafbeb51a2e5d70c4f2b020db86b5b05f6912351ceae9380f35b8a25ee12b02d26a1255d

test:
  secret_key_base: 74950f4a5634136c1c9c3192e53c5376485aad0afee0fb5e58cba15bb270242de2da45e1e39146c845be4645fcd8f657ca88edbfc2f8c92dc62edc0a880770a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
